[package]
name = "dupl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
glob = "0.3.1"
rusqlite = "0.29.0"
sha256 = "1.4.0"
tqdm = "0.6.0"
